Task 1: Регистрация пользователя
gryroach/theater-auth-service pull request #15
Opened 2024-12-08 19:05 UTC by KirillYarkov

2024-12-08 20:11 UTC, gryroach requested changes
Класс! Задача по факту решена, но немного надо порефачить

2024-12-08 20:11 UTC, gryroach commented on src/repositories/cache.py
> +class RedisCache(CacheRepository):
Может добавим суффикс `Repository`? Иначе приходится смотреть, что это за класс

2024-12-08 20:11 UTC, gryroach commented on src/repositories/user.py
> +    async def get_by_field(self, db: AsyncSession, field: str, value: str):
Хороший метод, можно добавить даже в базовый репозиторий. Это по факту фильтр, только возвращается только одна запись. Если может быть только одна запись, то надо проверять, что поле содержит ограничение уникальности. Ну или хотя бы проверять существование такого поля.

2024-12-08 20:11 UTC, gryroach commented on src/api/v1/user.py
> +    existing_user = await user_repo.get_by_field(db, "login", user_create.login)
Тут надо либо добавить проверку наличия поля в репозитории, либо получать поле из модели, чтобы поддерживать код было проще.

2024-12-08 20:11 UTC, gryroach commented on src/api/v1/user.py
> +    await token_service.set_session_version(str(user.id), 1)
Зачем в ручке расписывать логику, если уже есть `UserService` и он не используется?

2024-12-08 20:11 UTC, gryroach commented on src/services/user.py
> +        self.token_service = token_service
Мы предполагаем, что может использоваться какой-то другой сервис работы с токенами? Я не знаю, какие сделать абстрактные методы, чтобы потом не надо было переписывать UserService. Может хотя бы сделать TokenService сервисом по умолчанию, чтобы не надо было его постоянно импортировать.

2024-12-08 20:11 UTC, gryroach commented on src/services/base.py
Это где-то используется? На будущее добавил? Ты уже создал CacheRepository, CacheServiceInterface дублирует функционал.
Может пока уберем, а потом добавим, если надо. Не знаю, где может нам пригодиться в этом сервисе кеширование, мы в базу почти не лезем для получения данных

2024-12-08 20:11 UTC, gryroach commented on src/db/db.py
> +@as_declarative()
Круто, не знал про это!
Но может тогда не определять id и __tablename__ в модели User& И id определить, как в модели User

2024-12-09 11:38 UTC, KirillYarkov commented on src/api/v1/user.py
> +    existing_user = await user_repo.get_by_field(db, "login", user_create.login)
Сделал в базовом абстрактном классе

2024-12-09 15:50 UTC, KirillYarkov commented
Теперь таблицы будут называться как класс в единственном числе, норм?

2024-12-09 17:48 UTC, gryroach commented on src/api/v1/user.py
> +async def get_user_service() -> UserService:
Это можно вынести туда, где объявляется сам сервис, чтобы здесь логики не было и можно было переиспользовать

2024-12-09 17:48 UTC, gryroach commented on src/services/user.py
> +            raise HTTPException(
Не стоит здесь вызывать такое исключение. Этот сервис к самому http отношения не имеет. Лучше вызывать кастомное исключение и в ручке его перехватывать

2024-12-09 18:23 UTC, gryroach approved these changes

2024-12-09 18:23 UTC, merged